# Git
repo_url: "git@github.com:RobinMatter6/de2-project.git"
repo_dest: "/home/appuser/de-2-project"
repo_branch: "main"

# Auth
deploy_key_dir: "/home/ubuntu/cluster-keys"
cluster_keys_dir: "/home/appuser/cluster-keys"

