name: Deploy model to production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to prod server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: appuser
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /home/appuser/de-2-project
            git pull origin production
            cp dev_server/model_columns.pkl prod_server/model_columns.pkl
            cp dev_server/star_predictor_model.pkl prod_server/star_predictor_model.pkl
            cp dev_server/top_languages.pkl prod_server/top_languages.pkl
            docker compose -f prod_server/docker-compose.yml up -d --build
